version: '3.8'

services:
  train_phoneme:
    build: .
    container_name: LightningClassifier
    shm_size: '1gb'
    volumes:
      - .:/app
    command: bash -c "chmod +x /app/scripts/install_dependencies.sh && /app/scripts/install_dependencies.sh && bash"
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]